<a href="https://colab.research.google.com/github/samveddubey/ELM-CNN-/blob/main/Seq2Num.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

# RNA Sequence to Numerical Form Using OPT Algorithm
def convert_rna_to_sparse_matrix(sequence):
    # Define the mapping of 3-letter tuples to indices
    tuple_mapping = {
        'AAA': 1, 'AAC': 2, 'AAG': 3, 'AAU': 4,
        'ACA': 5, 'ACC': 6, 'ACG': 7, 'ACU': 8,
        'AGA': 9, 'AGC': 10, 'AGG': 11, 'AGU': 12,
        'AUA': 13, 'AUC': 14, 'AUG': 15, 'AUU': 16,
        'CAA': 17, 'CAC': 18, 'CAG': 19, 'CAU': 20,
        'CCA': 21, 'CCC': 22, 'CCG': 23, 'CCU': 24,
        'CGA': 25, 'CGC': 26, 'CGG': 27, 'CGU': 28,
        'CUA': 29, 'CUC': 30, 'CUG': 31, 'CUU': 32,
        'GAA': 33, 'GAC': 34, 'GAG': 35, 'GAU': 36,
        'GCA': 37, 'GCC': 38, 'GCG': 39, 'GCU': 40,
        'GGA': 41, 'GGC': 42, 'GGG': 43, 'GGU': 44,
        'GUA': 45, 'GUC': 46, 'GUG': 47, 'GUU': 48,
        'UAA': 49, 'UAC': 50, 'UAG': 51, 'UAU': 52,
        'UCA': 53, 'UCC': 54, 'UCG': 55, 'UCU': 56,
        'UGA': 57, 'UGC': 58, 'UGG': 59, 'UGU': 60,
        'UUA': 61, 'UUC': 62, 'UUG': 63, 'UUU': 64
    }

    # Initialize sparse matrix
    sparse_matrix = np.zeros((64, len(sequence) - 2))

    # Populate sparse matrix
    for j in range(len(sequence) - 2):
        three_letter_tuple = sequence[j:j+3]
        if three_letter_tuple in tuple_mapping:
            index = tuple_mapping[three_letter_tuple]
            sparse_matrix[index, j] = 1
        else:
            index = tuple_mapping[three_letter_tuple]
            sparse_matrix[index, j] = 0


    return sparse_matrix

rnasequence="GGCCGGCAUGGUCCCAGCCUCCUCGCUGGCGCCGGCUGGGCAACACCAUUGCACUCCGGUGGCGAAUGGGAC"
sparsematrix=convert_rna_to_sparse_matrix(rnasequence)
print(sparsematrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
import numpy as np

# RNA Sequence to Numerical Form Using OPT Algorithm
def convert_protein_to_sparse_matrix(sequence):
    # Define the mapping of 3-letter tuples to indices
    tuple_mapping = {
        'AAA': 1, 'AAC': 2, 'AAG': 3, 'AAU': 4,
        'ACA': 5, 'ACC': 6, 'ACG': 7, 'ACU': 8,
        'AGA': 9, 'AGC': 10, 'AGG': 11, 'AGU': 12,
        'AUA': 13, 'AUC': 14, 'AUG': 15, 'AUU': 16,
        'CAA': 17, 'CAC': 18, 'CAG': 19, 'CAU': 20,
        'CCA': 21, 'CCC': 22, 'CCG': 23, 'CCU': 24,
        'CGA': 25, 'CGC': 26, 'CGG': 27, 'CGU': 28,
        'CUA': 29, 'CUC': 30, 'CUG': 31, 'CUU': 32,
        'GAA': 33, 'GAC': 34, 'GAG': 35, 'GAU': 36,
        'GCA': 37, 'GCC': 38, 'GCG': 39, 'GCU': 40,
        'GGA': 41, 'GGC': 42, 'GGG': 43, 'GGU': 44,
        'GUA': 45, 'GUC': 46, 'GUG': 47, 'GUU': 48,
        'UAA': 49, 'UAC': 50, 'UAG': 51, 'UAU': 52,
        'UCA': 53, 'UCC': 54, 'UCG': 55, 'UCU': 56,
        'UGA': 57, 'UGC': 58, 'UGG': 59, 'UGU': 60,
        'UUA': 61, 'UUC': 62, 'UUG': 63, 'UUU': 64
    }

    # Initialize sparse matrix
    sparse_matrix = np.zeros((64, len(sequence) - 2))

    # Populate sparse matrix
    for j in range(len(sequence) - 2):
        three_letter_tuple = sequence[j:j+3]
        if three_letter_tuple in tuple_mapping:
            index = tuple_mapping[three_letter_tuple]
            sparse_matrix[index, j] = 1
        else:
            index = tuple_mapping[three_letter_tuple]
            sparse_matrix[index, j] = 0


    return sparse_matrix

rnasequence="GGCCGGCAUGGUCCCAGCCUCCUCGCUGGCGCCGGCUGGGCAACACCAUUGCACUCCGGUGGCGAAUGGGAC"
sparsematrix=convert_rna_to_sparse_matrix(rnasequence)
print(sparsematrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
!pip install biopython

In [20]:
from Bio import SeqIO
from Bio.SeqUtils import ProtParam
from Bio.SeqUtils.ProtParam import ProteinAnalysis

# Load the protein sequence
protein_sequence = "AVPETRPNHTIYINNLNEKIKKDELKKSLHAIFSRFGQILDILVSRSLKMRGQAFVIFKEVSSATNALRSMQGFPFYDKPMRIQYAKTDSDIIAKMK"

# Calculate the amino acid composition
analysed_seq = ProteinAnalysis(protein_sequence)
aacid_comp = analysed_seq.get_amino_acids_percent()

print("\nAmino acid percentage:\n", aacid_comp)

# Calculate the molecular weight
mol_weight = analysed_seq.molecular_weight()

print("\nMolecular weight: ", mol_weight)

# Calculate the Aromaticity
aromaticity = analysed_seq.aromaticity()

print("\nAromaticity: ", aromaticity)

# Calculate the instability index
instability_index = analysed_seq.instability_index()

print("\nInstability index: ", instability_index)



Amino acid percentage:
 {'A': 0.07216494845360824, 'C': 0.0, 'D': 0.05154639175257732, 'E': 0.041237113402061855, 'F': 0.061855670103092786, 'G': 0.030927835051546393, 'H': 0.020618556701030927, 'I': 0.10309278350515463, 'K': 0.1134020618556701, 'L': 0.07216494845360824, 'M': 0.041237113402061855, 'N': 0.05154639175257732, 'P': 0.041237113402061855, 'Q': 0.041237113402061855, 'R': 0.061855670103092786, 'S': 0.08247422680412371, 'T': 0.041237113402061855, 'V': 0.041237113402061855, 'W': 0.0, 'Y': 0.030927835051546393}

Molecular weight:  11189.969799999988

Aromaticity:  0.09278350515463918

Instability index:  43.76298969072163


In [24]:
#The protein_scale function in the ProtParam module of Biopython allows you to calculate a scaled value for each amino acid in a protein sequence based on a given scale. The WindowSize parameter specifies the size of the window (number of amino acids) over which the scaling is applied, and the Edge parameter determines how the edges of the sequence are handled.
from Bio.SeqUtils.ProtParam import ProteinAnalysis
from Bio.SeqUtils import ProtParam



from Bio.SeqUtils import ProtParam

def generate_custom_scale(protein_sequence):
    # Calculate properties of the sequence
    analysed_seq = ProtParam.ProteinAnalysis(protein_sequence)

    # Calculate amino acid composition
    aacid_comp = analysed_seq.get_amino_acids_percent()

    # Calculate molecular weight
    mol_weight = analysed_seq.molecular_weight()

    # Calculate aromaticity
    aromaticity = analysed_seq.aromaticity()

    # Calculate instability index
    instability_index = analysed_seq.instability_index()

    # Calculate secondary structure fraction
    ss_fraction = analysed_seq.secondary_structure_fraction()

    # Calculate the flexibility
    flexibility = analysed_seq.flexibility()

    # Define a scale based on the properties
    scale = {}
    for aa, percent in aacid_comp.items():
        # Example: Assign a scale value based on the percentage of the amino acid in the sequence
        scale[aa] = percent / 100.0  # Normalize the percentage to be between 0 and 1

    #print(mol_weight + list(aromaticity))

    # Example: Use other properties to modify the scale
    for aa in scale:
        scale[aa] *= (mol_weight + list(aromaticity) + list(instability_index) + list(ss_fraction) + list(flexibility)) / 5

    return scale

# Example usage
protein_sequence = "AVPETRPNHTIYINNLNEKIKKDELKKSLHAIFSRFGQILDILVSRSLKMRGQAFVIFKEVSSATNALRSMQGFPFYDKPMRIQYAKTDSDIIAKMK"
custom_scale = generate_custom_scale(protein_sequence)

# Use the custom scale
scaled_values = ProtParam.ProteinAnalysis(protein_sequence).protein_scale(custom_scale, window=5, edge='C')
print("Scaled values:", scaled_values)


TypeError: 'float' object is not iterable